project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "OBFUS.CA/TE"
  description: "Online Bank for Understanding Statistics, Caclulus, & Algebra:  Teenager Edition"
  navbar:
    background: primary
    search: true
    left:
      - text: "home"
        href: index.qmd
      - text: "courses"
        menu:
          - href: MTH1W/index.qmd
  

format:
  html:
    theme: lux
    toc: true
