project:
  type: website

website:
  title: "Interactive Math Space"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: walkthrough.qmd
        text: "Testing the Site"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true